### ISSUE TITLE
Problem showing Chinese characters

### ISSUE THREAD

**Issue by annabellehu** [parklab/nozzle#18] opened 2013-08-16 02:37 UTC
If using English coding or Unicode in the browser, Chinese characters failed to show correctly.

When using Chinese character coding, namely GBK, Nozzle report will collapse to a narrow window that couldn't be viewed properly. But, If maximize the browser window, the problem is gone.

**Comment by ngehlenborg** [comment] 2013-08-16 20:15
Thanks for reporting this issue. Can you please provide a sample HTML report and the corresponding R script?

**Comment by ngehlenborg** [comment] 2013-09-19 22:13
Unless you can provide me with a report with Chinese characters I will be unable to reproduce this issue.

**Comment by wenbostar** [comment] 2013-09-20 04:43
Hi:
Please see the screenshot below, I just want to see the report "http://gdac.broadinstitute.org/docs/nozzle/reports/paper.html" by using Chrome version  29.0.1547.62. But Nozzle report will collapse to a narrow window that couldn't be viewed properly. If maximize the browser window, the problem is gone.

![image](https://f.cloud.github.com/assets/5302110/1178413/d768522c-21ae-11e3-9072-9b77f072709f.png)

**Comment by ngehlenborg** [comment] 2013-09-30 20:02
@wenbostar This is unrelated to the original topic of this issue. Please open a new issue to report this problem (which I can't reproduce, it might be caused by browser plugins).

@annabellehu Without a sample report with Chinese characters I cannot address this issue. Closing for now.

**Closed as completed by ngehlenborg** 2013-09-30 20:02 UTC
Labels: bug
